GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Anastas",
    "number": "33335-343567345"
}

###
GET http://localhost:3001